branches:
  except:
    - gh-pages
    - win32-support
language: ruby
rvm:
  - "2.3.0"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: "1.9.3"
    - rvm: jruby-19mode
