language: ruby
rvm:
  - "2.0.0"
  - "1.9.3"
  - "1.8.7"
  - jruby-19mode
before_install:
  #- cd ext/timestamp ; ruby extconf.rb && make && mv timestamp.so ../../lib/ || ls -al ; cd ../..
  - gem install rake-compiler
  - rake compile
